### ISSUE TITLE
Are the Typescript definitions generated?

### ISSUE THREAD

**Issue by mathiasi** [snowcoders/boilerplate-emscripten-typescript#134]
I'm looking into a similar stack and came across this repo. I'm looking for a way to have auto generated Typescript definitions, so I was wondering if https://github.com/snowcoders/boilerplate-emscripten-typescript/blob/master/client-shared-js/client-shared-js.d.ts is somehow auto generated or manually specified? Could not find any evidence in the code that would indicate they are generated but I wanted to make sure.

**Comment by k2snowman69** [comment]
Sadly no; I also saw your message on the emscripten github repo about this as well. Honestly my investigations into generating the d.ts were never really fruitful and would never be able to be applied to the larger emscripten world but I would love the functionality because it would really tie this template project together.

Sorry I couldn't help you
